### ISSUE TITLE
Create precomputeCircularWave()

### ISSUE THREAD

**Issue by Andy-L-1** [WhenLifeHandsYouLemons/LED-Light-Wall#20]
Create a circular wave pattern

**Comment by WhenLifeHandsYouLemons** [comment]
Probably not super important or useful as we can't use this with any of our other wave types.

**Comment by WhenLifeHandsYouLemons** [comment]
Later can probably change it from using the pixel buffer to a custom version which uses the [Bresenham Circle Algorithm](https://github.com/WhenLifeHandsYouLemons/Shared-Coding-Files/blob/1d0d5a30700bc73a2e7da35d6230ff641501693c/LED%20lights/wave-explain.md). This would allow us to use precomputeColours and our other functions to display it at the same time as other types of waves.

**Comment by WhenLifeHandsYouLemons** [comment]
Used the Bresenham Circle Algorithm so that we could use other patterns at the same time.

**Comment by WhenLifeHandsYouLemons** [comment]
Also need to check whether the code works (can use the pygame version to check)
